repos:
   - repo: https://github.com/pre-commit/mirrors-mypy
     rev: v0.910
     hooks:
     - id: mypy
   - repo: https://github.com/psf/black
     rev: 21.9b0
     hooks:
     - id: black
   - repo: local
     hooks:
     - id: flake8
       name: flake8
       entry: flake8
       language: system
       types: [python]